version: '3.8'

services:
  mslf-backend:
    build: .
    container_name: mslf-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod  # Activate the 'prod' profile
      DB_PORT: 3306
      DB_NAME: railway
      DB_USER: root
      DB_PASSWORD: gVsPxMzRdmlLJXhcNhRSVCLvUZSDsTIb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
