pipeline {
    agent any

    environment {
        GITHUB_TOKEN = credentials('GITHUB-ACCESS-TOKEN')
    }

    stages {

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh './gradlew dependencies'
            }
        }

        stage('Build') {
            steps {
                githubNotify name: 'Build', summary: 'Building the project', status: 'IN_PROGRESS'
                sh './gradlew build'
                githubNotify name: 'Build', summary: 'Project built successfully', status: 'IN_PROGRESS'
            }
        }

        stage('Test') {
            steps {
                githubNotify name: 'Test', summary: 'Running tests', status: 'IN_PROGRESS'
                echo 'Running unit tests...'
                sh './gradlew test'
                githubNotify name: 'Test', summary: 'Tests completed successfully', status: 'IN_PROGRESS'
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging the application...'
                sh './gradlew bootJar'
            }
        }

        // stage('Archive Artifacts') {
        //     steps {
        //         echo 'Archiving the built artifact'
        //         archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
        //     }
        // }

    }

    post {
        success {
            githubNotify name: 'Build', summary: 'Build completed successfully', status: 'COMPLETED', conclusion: 'SUCCESS'        
        }
        failure {
            githubNotify name: 'Pipeline', summary: 'Pipeline failed', status: 'COMPLETED', conclusion: 'FAILURE'        
        }
    }
}
