spring:
  datasource:
      url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver # Ensure this is correctly specified
